#!/bin/bash

currentdir=$(pwd)
mkdir ~/.termitutor
cd ~/.termitutor
echo "${PS1@P}" > .set
echo "$currentdir" >> .set
echo "This is a sample file" > example.txt
echo "#!/bin/bash

print(\"This is a python file\")" > sample.py
chmod +x sample.py
