#!/bin/python

import os

def check(supp, act):
    if supp == act:
        return True
    else:
        return False

def inp(supp):
    run = input(setup[0])
    if check(supp, run):
        os.system(run)
    else:
        print("Please type in " + supp + " instead")
        inp(supp)
    return True

os.system("./setup")
user = os.getlogin()

setup = []
with open("/home/" + user + "/.termitutor/.set", "r") as s:
	setup = s.readlines()
	s.close()
setup = [sets[:-1] for sets in setup]

os.system("clear")
print("Welcome to TermiTutor!\nPlease type in \"ls\" to begin")
inp("ls")

#Cleaning up
os.system("rm -rf /home/" + user + "/.termitutor")
